#docker build -t calci3 .
#docker run -it --name cal_cont_by_yml -e ENVIRONMENT=development -v cal_val:/data --network mynetwork calci3 
services:
  calculator:
    build: .
    image: calci3
    container_name: cal_cont_by_yml
    stdin_open: true
    tty: true
    environment:
      - ENVIRONMENT=development
    volumes:
      - cal_val:/data
    networks: 
      - my_network
    command: python calculator.py
    depends_on:
      - redis
  redis:
    image: redis:7
    container_name: redis_server
    networks:
      - my_network
  # wna to define them here so that we can use them in other sservices as well , reusability
volumes:
  cal_val:
networks:
  my_network:

