name: Test Calculator
on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"   #ist = utc + 5:30 ie,ist=7:30 am
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Load code from repository
        uses: actions/checkout@v4
      - name: Set Python
        uses: actions/setup-python@v5
      - name: Pytest run
        run: pip install pytest
      - name: Run tests
        run: pytest
